package rs.ac.bg.fon.nprog.client.gui;

import rs.ac.bg.fon.nprog.library.domen.Recept;
import rs.ac.bg.fon.nprog.library.domen.Sastojak;
import java.util.List;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import rs.ac.bg.fon.nprog.client.komunikacija.KomunikacijaSaServerom;
import rs.ac.bg.fon.nprog.library.konstante.Operacije;
import rs.ac.bg.fon.nprog.library.transfer.KlijentskiZahtev;
import rs.ac.bg.fon.nprog.library.transfer.ServerskiOdgovor;

/**
 *
 * @author Nadia
 */
public class FrmReceptDetaljno extends JDialog {

	Recept r;

	/**
	 * Creates new form FrmReceptDetaljno
	 */
	public FrmReceptDetaljno(java.awt.Frame parent, boolean modal, Recept r) {
		super(parent, modal);
		initComponents();
		this.r = r;
		srediFormu();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		lblVremePripreme = new javax.swing.JLabel();
		lblNivoTezine = new javax.swing.JLabel();
		lblVrstaJela = new javax.swing.JLabel();
		lblKategorijaRecepta = new javax.swing.JLabel();
		lblOpisRecepta = new javax.swing.JLabel();
		txtNaziv = new javax.swing.JTextField();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtSastojci = new javax.swing.JTextArea();
		lblNaziv = new javax.swing.JLabel();
		lblSastojci = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		txtOpisRecepta = new javax.swing.JTextArea();
		txtVremePripreme = new javax.swing.JTextField();
		txtNivoTezine = new javax.swing.JTextField();
		txtVrstaJela = new javax.swing.JTextField();
		txtKategorijaRecepta = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		lblVremePripreme.setText("Vreme pripreme");

		lblNivoTezine.setText("Nivo težine");

		lblVrstaJela.setText("Vrsta jela");

		lblKategorijaRecepta.setText("Kategorija recepta");

		lblOpisRecepta.setText("Opis recepta");

		txtSastojci.setColumns(20);
		txtSastojci.setRows(5);
		jScrollPane1.setViewportView(txtSastojci);

		lblNaziv.setText("Naziv");

		lblSastojci.setText("Sastojci");

		txtOpisRecepta.setColumns(20);
		txtOpisRecepta.setRows(5);
		jScrollPane2.setViewportView(txtOpisRecepta);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addComponent(lblOpisRecepta)
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
								.addGroup(layout.createSequentialGroup().addComponent(lblSastojci)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(50, 50, 50))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addComponent(lblKategorijaRecepta)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114,
												Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(txtKategorijaRecepta,
														javax.swing.GroupLayout.PREFERRED_SIZE, 231,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(txtVrstaJela, javax.swing.GroupLayout.PREFERRED_SIZE, 231,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(txtNivoTezine, javax.swing.GroupLayout.PREFERRED_SIZE,
														231, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(txtVremePripreme, javax.swing.GroupLayout.PREFERRED_SIZE,
														231, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(68, 68, 68))))
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(lblNivoTezine).addComponent(lblVrstaJela))
										.addGap(0, 0, Short.MAX_VALUE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(lblNaziv).addComponent(lblVremePripreme))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124,
												Short.MAX_VALUE)
										.addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 236,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGap(65, 65, 65)))
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap(207, Short.MAX_VALUE).addComponent(jScrollPane2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(51, 51, 51))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGap(67, 67, 67)
						.addComponent(txtVremePripreme, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(30, 30, 30)
						.addComponent(txtNivoTezine, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(35, 35, 35)
						.addComponent(txtVrstaJela, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(45, 45, 45)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
								.createSequentialGroup()
								.addComponent(txtKategorijaRecepta, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55,
										Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblSastojci))
								.addGap(6, 6, 6).addComponent(lblOpisRecepta).addGap(113, 113, 113))
								.addGroup(layout.createSequentialGroup().addComponent(lblKategorijaRecepta)
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblNaziv))
						.addGap(26, 26, 26).addComponent(lblVremePripreme).addGap(36, 36, 36)
						.addComponent(lblNivoTezine).addGap(47, 47, 47).addComponent(lblVrstaJela)
						.addContainerGap(360, Short.MAX_VALUE)))
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap(446, Short.MAX_VALUE)
								.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(29, 29, 29))));

		pack();
	}// </editor-fold>

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JLabel lblKategorijaRecepta;
	private javax.swing.JLabel lblNaziv;
	private javax.swing.JLabel lblNivoTezine;
	private javax.swing.JLabel lblOpisRecepta;
	private javax.swing.JLabel lblSastojci;
	private javax.swing.JLabel lblVremePripreme;
	private javax.swing.JLabel lblVrstaJela;
	private javax.swing.JTextField txtKategorijaRecepta;
	private javax.swing.JTextField txtNaziv;
	private javax.swing.JTextField txtNivoTezine;
	private javax.swing.JTextArea txtOpisRecepta;
	private javax.swing.JTextArea txtSastojci;
	private javax.swing.JTextField txtVremePripreme;
	private javax.swing.JTextField txtVrstaJela;
	// End of variables declaration

	private void srediFormu() {
		this.setTitle("Prikaz recepta");
		if (r == null) {
			System.out.println("Recept ne sme da bude null!");
		}
		setLocationRelativeTo(null);

		popuniPraznaPolja();
	}

	private void popuniPraznaPolja() {
		txtKategorijaRecepta.setEditable(false);
		txtKategorijaRecepta.setText(r.getKategorijaRecepta().toString());
		txtNaziv.setEditable(false);
		txtNaziv.setText(r.getNaziv());
		txtNivoTezine.setEditable(false);
		txtNivoTezine.setText(r.getNivoTezine().toString());
		txtOpisRecepta.setEditable(false);
		txtOpisRecepta.setText(r.getOpisRecepta());
		txtSastojci.setEditable(false);
		popuniSastojke();
		txtVremePripreme.setEditable(false);
		txtVremePripreme.setText(r.getVremePripreme().toString());
		txtVrstaJela.setEditable(false);
		txtVrstaJela.setText(r.getVrstaJela().toString());
	}

	public void popuniSastojke() {
		List<Sastojak> sastojci;
		StringBuilder builder = new StringBuilder();
		KlijentskiZahtev kz = new KlijentskiZahtev();
		kz.setOperacija(Operacije.VRATI_SASTOJKE_RECEPTA);
		kz.setParametar(r);
		KomunikacijaSaServerom.getInstance().posaljiZahtev(kz);
		ServerskiOdgovor so = KomunikacijaSaServerom.getInstance().primiOdgovor();
		sastojci = (List<Sastojak>) so.getOdgovor();
		if (sastojci == null) {
			JOptionPane.showMessageDialog(this, "Nema sastojaka za ovaj recept");
		} else {
			for (int i = 0; i < sastojci.size(); i++) {
				builder.append(sastojci.get(i));
				builder.append("\n");
			}
		}
		txtSastojci.setText(builder.toString());
	}
}